apiVersion: batch/v1
kind: Job
metadata:
  name: keyclock-job
spec:
  template:
    metadata:
      name: keyclock-pod
    spec:
      containers:
      - name: keyclock-container
        image: paichayon1/keycloakscript:1.1
        command: ["sh", "/creategroup.sh", "$(kuser)", "$(kpass)", "$(kurl)", "$(krealm)", "$(kgroup)"]
        env:
          - name: kuser
            valueFrom:
              secretKeyRef:
                name: mykeycloak
                key: kuser
          - name: kpass
            valueFrom:
              secretKeyRef:
                name: mykeycloak
                key: kpass
          - name: kurl
            valueFrom:
              secretKeyRef:
                name: mykeycloak
                key: kurl
          - name: krealm
            valueFrom:
              secretKeyRef:
                name: mykeycloak
                key: krealm
          - name: kgroup
            valueFrom:
              secretKeyRef:
                name: mykeycloak
                key: kgroup
      restartPolicy: Never
