apiVersion: batch/v1
kind: Job
metadata:
  name: keyclock-job
spec:
  template:
    metadata:
      name: keyclock-pod
    spec:
      containers:
      - name: keyclock-container
        image: paichayon1/keycloakscript:1.1
        command: ["sh", "/creategroup.sh", "admin", "xxxxxxx", "https://keycloak-keycloak.apps.524vf.dynamic.opentlc.com", "basic", "group-test1"]
      restartPolicy: Never
