variables:
  realm:
    value: "basic"
    description: "KeyCloak realm Name"  

  groupname:
    value: ""
    description: "KeyCloak Group Name"


before_script:
  - chmod +x ./creategroup.sh

stages:
  - runscript

runscript:       # This job runs in the build stage, which runs first.
  stage: runscript
  script:
    - pwd
    - ls -la
    - ./creategroup.sh $kuser $kpass $kurl $realm $groupname
  #when: manual
